### PR TITLE
NiFi 1.19 update

### PR DESCRIPTION
**Pull request by Chaffelson**
- RegistryClientEntity is renamed to FlowRegistryClientEntity for clarity in NiFi-1.19, along with other related classes - consequently ControllerApi().create_registry_client is now ControllerApi().create_flow_registry_client, etc.
- urllib3 advises that HTTPResponse.getheaders() will soon be deprecated, moving to HTTPResponse.headers as advised
- The NiFi API call to create a registry client no longer errors when a duplicate name is requested, however it still errors if you attempt to update a registry client with a non-unique name. Commenting out this test for now as it is not a critical requirement.
- The NiFi API no longer removes the Registry URI when deleting the object, removing this test from the set and replacing with a test that ensures the client can no longer be retrieved once deleted.
- Ensure newer versions of flake8 exclude autogenerated client files from tests

### CODE REVIEW

**Comment by ottobackwards** [comment]
Are these breaking changes wrt the RegistryClient* changes?

**Comment by ottobackwards** [comment]
I know you want to match the nifi version, but maybe a README notice or Upgrading.md or something?

**Comment by Chaffelson** [comment]
versioning.py is backwards compatible except for the one minor behaviour change in the API when it comes to creating a new NiFi Registry client.
The renamed calls are within the low level client and are effectively wrapped by versioning.py, so unless some user is directly calling those API calls people won't be affected, and if they are it is a very minor renaming of the method.

**Comment by ottobackwards** [comment]
OK

**Comment by ottobackwards** [comment]
LGTM +1 FWIW

**Pull request merged**
