### PR TITLE
NiFi 1.23.2 update

### PR DESCRIPTION
**Pull request by Hexoplon**
* Updated clients and Docker for 1.23.2
* Fixed error in swagger template causing an attribute not found error on RESTResponse objects
* Updated pip dependencies to fix security issues highlighted by Snyk
* Upped version to 0.20.0

Passes default, security and regression tests

### CODE REVIEW

**Comment by ottobackwards** [comment]
I think the changes to the pylintrc should be their own PR and discussion, as you do not just move to a new template, but you add different configuration.

For something like that I would want a new PR, which in the description spoke to what was added and why.

**Comment by Hexoplon** [comment]
> I think the changes to the pylintrc should be their own PR and discussion, as you do not just move to a new template, but you add different configuration.
> 
> For something like that I would want a new PR, which in the description spoke to what was added and why.
> 
> This isn't to say I'm against these changes, but as a reviewer, this should be it's own issue mr

I see what you mean and agree! I'll remove that commit.

**Comment by Chaffelson** [comment]
Hi @Hexoplon thanks for taking the time to put this together!

Would you please mind [signing your commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)?

I will have time in the next few days to test and merge this.

**Comment by Hexoplon** [comment]
@Chaffelson The commits are now signed! Sorry for taking a while

**Comment by Chaffelson** [comment]
Did some testing on this today - generally looks good, I'm mostly having issues with Python and requirement versions.

Can you share what OS / Python versions you tested on? I'll try to match yours and then branch into the rest.

**Comment by Hexoplon** [comment]
@Chaffelson I'm not at my computer until next week, but pretty sure I used python 3.9.18 on Ubuntu, running in WSL2. Have used the packaged version with newest dependencies on RHEL8 running python 3.9.16 as well, but not ran through the tests there.
If you need more info I'll get it next week

**Comment by Chaffelson** [comment]
No, that's very helpful already thank you - I'll switch from testing the oldest compatible to matching your test and then seeing if I can work back and remove some of the stuff that simply won't work anymore in Py2 and Centos7.

**Comment by ottobackwards** [comment]
like Centos7 and py2?  removing them? ;)

**Comment by Chaffelson** [comment]
Apologies for the delay - I haven't forgotten about this but we're into conference season now and my day job is keeping me very busy. This is on my to-do list.

**Comment by Chaffelson** [comment]
Tested on Windows 10 with WSL2 running Python3.8 in Pycharm Pro. Works great.
I had to make some modifications to get the tests to run, but they are not related to the PR.

```
virtualenv>=16.0.0,<20.22
tox>=2.9.1,<4.0
```

Virtualenv dropped Python2 support after 20.22 so we'll need to pin it until we do the same.
The tests were written for Tox 3, and Pycharm is not happy with Tox4, so we'll stick with 3 for now.

I'll put these into a small PR to go into the next release.

**Comment by dleditschke** [comment]
@Chaffelson are there plans to release official support for NiFi / NiFi Registry >1.17.0?

**Comment by Chaffelson** [comment]
Hi @dleditschke yes I think we can test all the way up to include the latest 1.x line.
I haven't done any work on the 2.x line as yet, as NiPy has been relatively stable and I have been busy with my day job.
I shall book a day out of my projects to test and cut a release this month, would that be suitable?

**Pull request merged**
